#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage:
  tools/materialize_deepseek_v3_bf16.sh [--dest <path>]

Environment overrides:
  SRC_BF16_SNAPSHOT   Existing BF16 snapshot directory to reuse
  SRC_META_DIR        Directory containing official config/tokenizer/modeling files
  DEST_DIR            Destination local DeepSeek-V3-BF16 directory

Notes:
  - Large weight shards are symlinked from SRC_BF16_SNAPSHOT to avoid another copy.
  - config.json is regenerated from the BF16 snapshot with num_nextn_predict_layers=0.
EOF
}

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
REPO_ROOT=$(cd -- "$SCRIPT_DIR/.." && pwd)
WORKSPACE_ROOT=$(cd -- "$REPO_ROOT/.." && pwd)

SRC_BF16_SNAPSHOT="${SRC_BF16_SNAPSHOT:-/lustre/fsw/coreai_dlalgo_llm/users/pdalmia/hf_home/hub/models--unsloth--DeepSeek-V3-0324-BF16/snapshots/814ea69b14b23e252f4367b114e73b39b8b05049}"
SRC_META_DIR="${SRC_META_DIR:-/lustre/fsw/coreai_dlalgo_llm/users/pdalmia/DeepSeek-V3-HF-meta}"
DEST_DIR="${DEST_DIR:-/lustre/fsw/coreai_dlalgo_llm/users/pdalmia/DeepSeek-V3-BF16}"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --dest)
      DEST_DIR="$2"
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
  shift
done

if [[ ! -d "$SRC_BF16_SNAPSHOT" ]]; then
  echo "BF16 snapshot not found: $SRC_BF16_SNAPSHOT" >&2
  exit 2
fi

if [[ ! -d "$SRC_META_DIR" ]]; then
  echo "Meta directory not found: $SRC_META_DIR" >&2
  exit 2
fi

for required in modeling_deepseek.py configuration_deepseek.py tokenizer.json tokenizer_config.json config.json; do
  if [[ ! -f "$SRC_META_DIR/$required" ]]; then
    echo "Required meta file missing: $SRC_META_DIR/$required" >&2
    exit 2
  fi
done

if [[ -e "$DEST_DIR" && ! -d "$DEST_DIR" ]]; then
  echo "Destination exists and is not a directory: $DEST_DIR" >&2
  exit 2
fi

mkdir -p "$DEST_DIR"

find "$DEST_DIR" -maxdepth 1 -type l -name 'model-*.safetensors' -delete
find "$DEST_DIR" -maxdepth 1 -type l -name 'model.safetensors.index.json' -delete

for shard in "$SRC_BF16_SNAPSHOT"/model-*.safetensors; do
  ln -sfn "$shard" "$DEST_DIR/$(basename "$shard")"
done
ln -sfn "$SRC_BF16_SNAPSHOT/model.safetensors.index.json" "$DEST_DIR/model.safetensors.index.json"

cp "$SRC_META_DIR/modeling_deepseek.py" "$DEST_DIR/modeling_deepseek.py"
cp "$SRC_META_DIR/configuration_deepseek.py" "$DEST_DIR/configuration_deepseek.py"
cp "$SRC_META_DIR/tokenizer.json" "$DEST_DIR/tokenizer.json"
cp "$SRC_META_DIR/tokenizer_config.json" "$DEST_DIR/tokenizer_config.json"

jq 'del(.quantization_config) | .num_nextn_predict_layers = 0' \
  "$SRC_BF16_SNAPSHOT/config.json" > "$DEST_DIR/config.json"

cat > "$DEST_DIR/README.codex.txt" <<EOF
Generated by $SCRIPT_DIR/$(basename "$0")
BF16 weights source: $SRC_BF16_SNAPSHOT
Metadata source: $SRC_META_DIR
Changes:
- config.json: quantization_config removed
- config.json: num_nextn_predict_layers set to 0
- modeling_deepseek.py/configuration_deepseek.py/tokenizer files copied from official DeepSeek HF metadata repo
- model shards symlinked from existing BF16 snapshot
EOF

shard_count=$(find "$DEST_DIR" -maxdepth 1 -type l -name 'model-*.safetensors' | wc -l | tr -d ' ')
printf 'dest_dir=%s\n' "$DEST_DIR"
printf 'shard_count=%s\n' "$shard_count"
printf 'config_num_nextn_predict_layers=%s\n' "$(jq '.num_nextn_predict_layers' "$DEST_DIR/config.json")"
printf 'has_modeling=%s\n' "$([[ -f "$DEST_DIR/modeling_deepseek.py" ]] && echo yes || echo no)"
